# Generated by Django 5.2.6 on 2025-11-20 12:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0002_alter_customuser_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('task_created', 'Task Created'), ('task_updated', 'Task Updated'), ('task_completed', 'Task Completed'), ('task_assigned', 'Task Assigned'), ('comment_added', 'Comment Added'), ('file_uploaded', 'File Uploaded'), ('project_created', 'Project Created'), ('team_joined', 'Team Joined'), ('message_sent', 'Message Sent'), ('meeting_scheduled', 'Meeting Scheduled')], max_length=50)),
                ('description', models.TextField()),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='users.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['team', 'created_at'], name='activity_fe_team_id_84460b_idx'), models.Index(fields=['user', 'created_at'], name='activity_fe_user_id_7ec0ef_idx'), models.Index(fields=['content_type', 'object_id'], name='activity_fe_content_7c84fe_idx')],
            },
        ),
    ]
