# Generated by Django 5.2.6 on 2025-10-04 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(choices=[('priority', 'Priority Adjustment'), ('timing', 'Timing Suggestion'), ('assignment', 'Task Assignment'), ('deadline', 'Deadline Adjustment'), ('breakdown', 'Task Breakdown')], max_length=50)),
                ('suggestion', models.TextField()),
                ('reasoning', models.TextField(blank=True)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_applied', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
            options={
                'ordering': ['-confidence_score', '-created_at'],
            },
        ),
    ]
